/**
 * @file    html_page.cpp
 * @brief   嵌入式 HTML（HTTP 头 ~117B + body ~4031B → 三次 CIPSEND @2048 发完）
 */

#include <stdint.h>

/* C++ 中 const 全局默认内部链接，需 extern 才能供 esp8266.cpp 引用 */
extern const char html_page[] =
"<!DOCTYPE html><html><head><meta charset=utf-8>"
"<meta name=viewport content=\"width=device-width,initial-scale=1\">"
"<title>TouchGesture</title><style>"
"*{box-sizing:border-box;margin:0;padding:0}"
"body{font:13px sans-serif;background:#0d0d1a;color:#ccc;padding:10px;text-align:center}"
"h2{color:#0ff;font-size:15px;margin:6px 0 8px}"
".c{background:#16213e;border-radius:10px;padding:10px;margin:6px auto;max-width:300px;text-align:left}"
".ch{color:#8cf;font-size:11px;font-weight:700;margin-bottom:6px}"
".row{display:flex;justify-content:center;gap:5px;margin:4px 0}"
".b{width:38px;height:38px;border-radius:50%;border:2px solid #333;background:#1a1a2e;"
"font-size:9px;display:flex;align-items:center;justify-content:center;color:#666}"
".b.on{border-color:#0ff;background:#0ff;color:#000;box-shadow:0 0 8px #0ff}"
".g{font:700 20px sans-serif;color:#0f0;min-height:26px;text-align:center;padding:4px 0}"
".leds{display:flex;justify-content:space-around;padding:2px 0}"
".led{text-align:center;width:52px}"
".dot{width:22px;height:22px;border-radius:50%;margin:0 auto 3px;border:2px solid #333;background:#222}"
".dot.on{border-color:#f80}"
".l1.on{background:#f55;box-shadow:0 0 8px #f44}"
".l2.on{background:#5f5;box-shadow:0 0 8px #4f4}"
".l3.on{background:#ff3;box-shadow:0 0 8px #fc0}"
".l4.on{background:#5af;box-shadow:0 0 8px #4ae}"
".bar{height:4px;background:#1a1a2e;border-radius:2px;margin-top:3px}"
".fill{height:100%;border-radius:2px;background:linear-gradient(90deg,#f80,#fc0)}"
".ln{font-size:10px;color:#888}"
".ap{font:10px monospace;color:#6c6;padding:2px 0}"
".log{font-size:10px;max-height:80px;overflow-y:auto;color:#aaa}"
".log div{padding:1px 0;border-bottom:1px solid #1a1a2e}"
".ts{color:#555;margin-right:4px}"
".st{font-size:10px;color:#555;text-align:right;margin-top:4px}"
"</style></head><body>"
"<h2>TouchGesture</h2>"
"<div class=c><div class=ch>Touch</div>"
"<div class=row><div class=b id=tU>U</div></div>"
"<div class=row><div class=b id=tL>L</div>"
"<div class=b style=\"border:none;color:#333\">&#x271A;</div>"
"<div class=b id=tR>R</div></div>"
"<div class=row><div class=b id=tD>D</div></div></div>"
"<div class=c><div class=ch>Gesture</div><div class=g id=gN>--</div></div>"
"<div class=c><div class=ch>LED</div><div class=leds>"
"<div class=led><div class=\"dot l1\" id=l1></div>"
"<div class=bar><div class=fill id=b1 style=width:0></div></div>"
"<div class=ln>CH1</div></div>"
"<div class=led><div class=\"dot l2\" id=l2></div>"
"<div class=bar><div class=fill id=b2 style=width:0></div></div>"
"<div class=ln>CH2</div></div>"
"<div class=led><div class=\"dot l3\" id=l3></div><div class=ln>CH3</div></div>"
"<div class=led><div class=\"dot l4\" id=l4></div><div class=ln>CH4</div></div>"
"</div></div>"
"<div class=c><div class=ch>APDS-9960</div><div class=ap id=ap>--</div></div>"
"<div class=c><div class=ch>Log</div>"
"<div class=log id=hi></div>"
"<div class=st id=st></div></div>"
"<script>"
"var Z='--,Tap,Up,Down,Left,Right,Long,Dbl'.split(','),pg=0,ok=0;"
"function u(){fetch('/api/state').then(function(r){return r.json()}).then(function(d){"
"var t=d.touch,k=['tU','tL','tR','tD'],i;"
"for(i=0;i<4;i++)document.getElementById(k[i]).className='b'+(t[i]?' on':'');"
"var ef=d.gesture,n=document.getElementById('gN');"
"if(d.last_g>0&&(d.t-d.last_gt)<2500)ef=d.last_g;"
"if(ef>0){n.textContent=Z[ef]||('G'+ef);n.style.opacity=1;"
"if(ef!==pg){var h=document.getElementById('hi'),e=document.createElement('div');"
"e.innerHTML='<span class=ts>'+(d.t/1000).toFixed(1)+'s</span>'+(Z[ef]||ef);"
"h.insertBefore(e,h.firstChild);if(h.children.length>10)h.removeChild(h.lastChild)}"
"pg=ef}else if(pg>0){n.style.opacity=.3;pg=0}"
"for(i=1;i<=4;i++){document.getElementById('l'+i).className='dot l'+i+(d.led[i-1]?' on':'')}"
"document.getElementById('b1').style.width=d.bri[0]+'%';"
"document.getElementById('b2').style.width=d.bri[1]+'%';"
"if(d.apds){var a=d.apds;document.getElementById('ap').textContent="
"'ok:'+a.ok+' id:'+a.id+' gv:'+a.gv+' gc:'+a.gc}"
"ok++;document.getElementById('st').textContent='#'+ok+' '+new Date().toTimeString().slice(0,8)"
"}).catch(function(e){document.getElementById('st').textContent='ERR'})"
".finally(function(){setTimeout(u,700)})}u();"
"</script></body></html>"
;

extern const uint16_t html_page_len = sizeof(html_page) - 1;
